---
- name: Set up private virtual network
  hosts: debian_host
  gather_facts: no
  become: yes
  tasks:

    - name: Gather facts
      setup:

    - name: Check if OS is Debian
      fail:
        msg: "This playbook can only be run on Debian. Exiting."
      when: ansible_distribution != 'Debian'

    - name: Create private isolated virtual network
      virt_net:
        name: private_network
        mode: isolated
        state: present
