---
- name: Set up private virtual isolated network
  hosts: all
  gather_facts: no
  become: yes
  tasks:

    - name: Gather facts
      setup:

    - name: Check if OS is Debian
      fail:
        msg: "This playbook can only be run on Debian. Exiting."
      when: ansible_distribution != 'Debian'

    - name: Ensure python3-lxml package is installed
      apt:
        name: python3-lxml
        state: present
      when: ansible_os_family == "Debian"

    - name: Create private isolated virtual network
      virt_net:
        command: define
        name: private_network
        xml: "{{ lookup('file', 'isolated_network.xml') }}"
        state: present

    - name: Activate (start) private isolated virtual network
      virt_net:
        command: start
        name: private_network
        state: active

    - name: Ensure private_network is set to autostart
      command:
        cmd: virsh net-autostart private_network

