---
- name: Setup nftables
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Gather facts
      setup:

    - name: Check if OS is Debian
      fail:
        msg: "This playbook can only be run on Debian. Exiting."
      when: ansible_distribution != 'Debian'

    - name: Install nftables
      apt:
        name:
          - nftables
        state: present

    - name: Deploy nftables configuration
      template:
        src: nftables.j2
        dest: /etc/nftables.conf

    - name: Ensure routing is enabled
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^net.ipv4.ip_forward'
        line: 'net.ipv4.ip_forward=1'

    - name: Reload sysctl settings
      command:
        cmd: sysctl -p
